stages:
  - build

build:windows-ldc-x86_64:
  stage: build
  tags: [windows, x86_64]
  script: OS=windows DC=ldc2 TARGET=x86_64 WINDOWS_PLATFORM=x64 ./build.sh
  artifacts:
    paths:
      - psd/x64/Release/psd.lib
      - psd/x64/Release/psd.psd

build:windows-ldc-x86:
  stage: build
  tags: [windows, x86]
  script: OS=windows DC=ldc2 TARGET=x86 WINDOWS_PLATFORM=x86 ./build.sh
  artifacts:
    paths:
      - psd/Release/psd.lib
      - psd/Release/psd.psd

build:ubuntu-ldc-x86_64:
  stage: build
  tags: [ubuntu, x86_64]
  script: OS=linux DC=ldc2 TARGET=x86_64 ./build.sh
  artifacts:
    paths:
      - libpsd.a

build:osx-x86_64:
  stage: build
  tags: [osx, x86_64]
  script: OS=macos DC=ldc2 TARGET=x86_64-apple-macosx10.12 MACOSX_DEPLOYMENT_TARGET=10.12 ./build.sh
  artifacts:
    paths:
      - libpsd.a

build:osx-arm64:
  stage: build
  tags: [osx]
  script: OS=macos DC=ldc2 TARGET=arm64-apple-macosx12.0 MACOSX_DEPLOYMENT_TARGET=12.0 ./build.sh
  artifacts:
    paths:
      - libpsd.a

build:ios-arm64:
  stage: build
  tags: [osx]
  script: OS=ios DC=ldc2 TARGET=arm64-apple-ios16.0 IPHONEOS_DEPLOYMENT_TARGET=16.0 ./build.sh
  artifacts:
    paths:
      - libpsd.a

build:ios_simulator-x86_64:
  stage: build
  tags: [osx]
  script: OS=ios DC=ldc2 TARGET=x86_64-apple-ios16.0-simulator IPHONEOS_DEPLOYMENT_TARGET=16.0 ./build.sh
  artifacts:
    paths:
      - libpsd.a
